import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#fff',
  },
  container: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 6,
    backgroundColor: '#fff',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 8,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '600',
    letterSpacing: 0.2,
    color: '#171717',
    marginLeft: 2,
  },
  scanBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#ECECEC',
    borderRadius: 14,
    padding: 12,
    marginVertical: 10,
    backgroundColor: '#f8faff',
  },
  scanIcon: {
    marginRight: 10,
    backgroundColor: '#e5effa',
    padding: 7,
    borderRadius: 8,
  },
  scanTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#212121',
    marginBottom: 1,
  },
  scanDesc: {
    color: '#888',
    fontSize: 13,
  },
  scanBtn: {
    color: '#178BFE',
    fontWeight: 'bold',
    marginLeft: 10,
    fontSize: 14,
  },
  formCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 18,
    marginTop: 3,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    borderWidth: 1.5,
    borderColor: '#f2f2f2',
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111',
    marginBottom: 10,
  },
  genderRow: {
    flexDirection: 'row',
    marginBottom: 18,
  },
  genderBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#f3f3f3',
    marginRight: 8,
    alignItems: 'center',
  },
  genderBtnActive: {
    backgroundColor: '#FF9800',
  },
  genderText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#222',
  },
  genderTextActive: {
    color: '#fff',
  },
  fieldLabel: {
    fontSize: 13,
    color: '#888',
    marginTop: 7,
    marginBottom: 2,
    marginLeft: 2,
    fontWeight: '500',
    letterSpacing: 0.6,
  },
  input: {
    height: 45,
    borderRadius: 22,
    backgroundColor: '#fafafa',
    paddingHorizontal: 16,
    fontSize: 17,
    marginBottom: 2,
    borderWidth: 1,
    borderColor: '#ededed',
    color: '#222',
    fontWeight: 'bold',
  },
  photoBox: {
    backgroundColor: '#CBCBCB',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    height: 110,
    marginBottom: 16,
    marginTop: 0,
    overflow: 'hidden',
  },
  photoText: {
    fontSize: 28,
    color: '#181818',
    fontWeight: '500',
  },
  photoPreview: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    borderRadius: 14,
  },
  confirmBtn: {
    backgroundColor: '#FF9800',
    borderRadius: 18,
    alignItems: 'center',
    paddingVertical: 16,
    marginBottom: 18,
  },
  confirmText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.3,
  },
  modalBG: {
    flex: 1,
    backgroundColor: '#00000088',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 18,
    paddingBottom: Platform.OS === 'ios' ? 38 : 18,
  },
  modalBtn: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  modalBtnText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  divider: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: 4,
  },
  modalCancel: {
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  modalCancelText: {
    color: '#FF9800',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
export default styles;
