import { StyleSheet } from 'react-native';
// import Color from '../../../../../Theme/Color';
``
const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderColor: '#EFEFEF',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  backArrow: {
    fontSize: 28,
    color: '#111',
    marginRight: 10,
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#222',
    letterSpacing: 0.1,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#a8a8a8',
    fontWeight: '400',
  },
  clearText: {
    color: '#3E70FF',
    fontWeight: '500',
    fontSize: 14,
  },
  section: {
    marginHorizontal: 16,
    marginTop: 18,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 1,
    borderWidth: 1,
    borderColor: '#F1F1F1',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#181818',
    marginBottom: 10,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 7,
    gap: 8,
    flexWrap: 'wrap',
  },
  optionBtn: {
    minWidth: 110,
    flex: 1,
    backgroundColor: '#fafafa',
    borderRadius: 12,
    paddingVertical: 14,
    marginRight: 7,
    marginBottom: 7,
    borderWidth: 1,
    borderColor: '#f3f3f3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionText: {
    fontSize: 15,
    color: '#A5A5A5',
    fontWeight: '600',
    textAlign: 'center',
  },
  optionLabel: {
    fontSize: 11,
    fontWeight: '400',
    color: '#999',
  },
  optionPrice: {
    fontSize: 13,
    color: '#C8C8C8',
    fontWeight: '400',
  },
  selectedOption: {
    backgroundColor: '#FFF6ED',
    borderColor: '#F49B24',
    borderWidth: 1.5,
  },
  selectedOptionText: {
    color: '#F49B24',
    fontWeight: '700',
  },
  airlineBtn: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EDEDED',
    marginRight: 7,
    marginBottom: 7,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    minWidth: 130,
    minHeight: 50,
  },
  selectedAirline: {
    borderColor: '#F49B24',
    backgroundColor: '#FFF6ED',
  },
  airlineLogo: {
    height: 30,
    width: 85,
    resizeMode: 'contain',
  },
  applyBtn: {
    backgroundColor: '#F49B24',
    marginHorizontal: 18,
    borderRadius: 24,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 25,
    marginBottom: 22,
  },
  applyBtnText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
});

export default styles;
